version: 0.1

phases:
  pre_build:
    commands:
      - mkdir -p $GOPATH/src/github.com/intel-hpdd/lemur && cp -a . $_ && cd $_ && rm -fr vendor/github.com/intel-hpdd/logging/debug/examples && rm -fr uat && go get -v ./... && go get -v github.com/fortytw2/leaktest && go test -v $(go list ./... | egrep -v '(*vendor/*|*uat/*)' )
  build:
    commands:
      - echo Build started on `date`
      - make local-rpm
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /root/rpmbuild/RPMS/x86_64/*.rpm
    - /root/rpmbuild/SRPMS/*.src.rpm
  discard-paths: yes
